name: CI
on: [push]
jobs:
  prettier:
    name: 💄 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install package dependencies
        uses: bahmutov/npm-install@v1

      - name: Run script
        run: yarn format:ci

  eslint:
    name: 🪀 ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install package dependencies
        uses: bahmutov/npm-install@v1

      - name: Run script
        run: yarn lint:ci

  jest:
    name: 🎪 Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install package dependencies
        uses: bahmutov/npm-install@v1

      - name: Run script
        run: yarn test:ci

  cypress:
    name: 🌲 Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Restore Next.js cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock')}}

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev
          wait-on: "http://localhost:3000"
